version: "3.7"

services:
    app:
        build:
            context: .
            target: web_app
        links:
            - db
        ports:
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        restart: on-failure

    db:
        build:
            context: .
            target: database
        links:
            - postgres
        expose:
            - "8081"
        restart: on-failure

    pgadmin:
        env_file:
            - database/src/main/resources/pgadmin.env
        image: dpage/pgadmin4
        links:
            - postgres
        ports:
            - target: 80
              published: 5432
              protocol: tcp
              mode: host

    postgres:
        env_file:
            - database/src/main/resources/database.env
        image: postgres
        expose:
            - "5432"
        restart: on-failure
        volumes:
            - diceroller:/var/lib/postgresql
            - ./database/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    diceroller:
