version: "3.7"
services:
    app:
        build:
            context: .
            target: web_app
        ports:
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        links:
            - db
        restart: on-failure

    db:
        build:
            context: .
            target: database
        ports:
            - target: 8080
              published: 8081
              protocol: tcp
              mode: host
        restart: on-failure

    postgres:
        image: postgres
        restart: on-failure
