version: "3.7"

services:
    app:
        build:
            context: .
            target: web_app
        links:
            - db
        ports:
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        restart: on-failure

    db:
        build:
            context: .
            target: database
        links:
            - postgres
        expose:
            - "8081"
        restart: on-failure

    postgres:
        image: postgres
        env_file:
            - database/src/main/resources/database.env
        expose:
            - "5432"
        restart: on-failure
        volumes:
            - diceroller:/var/lib/postgresql

volumes:
    diceroller:
